---
- name: Forward port 80 to centralServer:8080
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    match: tcp
    destination_port: "8080"
    jump: DNAT
    to_destination: "192.168.0.2:80"

- name: Allow output traffic to port 8080
  iptables:
    table: nat
    chain: OUTPUT
    protocol: tcp
    destination_port: "8080"
    jump: DNAT
    to_destination: "192.168.0.2:80"

- name: Enable masquerade for internal net
  iptables:
    table: nat
    chain: POSTROUTING
    jump: MASQUERADE

- name: Create static route to internal network
  shell: "ip route add 192.168.0.0/16 via 192.168.250.2"
  ignore_errors: yes
